# Generated by Django 5.1.6 on 2025-02-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='slug',
        ),
        migrations.AddField(
            model_name='destination',
            name='listings',
            field=models.IntegerField(default=10),
        ),
    ]
